=== Chaste/Chaste/heart/src/io/ChasteParameters_1_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="time_type">
      <xs:simpleContent>
          <xs:extension base="xs:decimal">
          <xs:attribute name="unit" type="xs:string" use="required" fixed="ms"/>
        </xs:extension>
      </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="dimensionless_type">
      <xs:simpleContent>
          <xs:extension base="xs:decimal">
          <xs:attribute name="unit" type="xs:string" use="required" fixed="dimensionless"/>
        </xs:extension>
      </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="conductivity_type">
      <xs:simpleContent>
          <xs:extension base="xs:decimal">
          <xs:attribute name="unit" type="xs:string" use="required" fixed="mS/cm"/>
        </xs:extension>
      </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="stimulus_strength_type">
      <xs:simpleContent>
          <xs:extension base="xs:decimal">
          <xs:attribute name="unit" type="xs:string" use="required" fixed="uA/cm^3"/>
        </xs:extension>
      </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="inverse_length_type">
      <xs:simpleContent>
          <xs:extension base="xs:decimal">
          <xs:attribute name="unit" type="xs:string" use="required" fixed="1/cm"/>
        </xs:extension>
      </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="capacitance_type">
      <xs:simpleContent>
          <xs:extension base="xs:decimal">
          <xs:attribute name="unit" type="xs:string" use="required" fixed="uF/cm^2"/>
        </xs:extension>
      </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="location_type">
      <xs:choice>
      <xs:element name="Cuboid" type="box_type"/>
    </xs:choice>
    <xs:attribute name="unit" type="xs:string" use="required" fixed="cm"/>
  </xs:complexType>

  <xs:simpleType name="domain_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Mono"/>
      <xs:enumeration value="Bi"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ionic_models_available_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Fox2002BackwardEuler"/>
      <xs:enumeration value="LuoRudyIBackwardEuler"/>
      <xs:enumeration value="LuoRudyI"/>
      <xs:enumeration value="FaberRudy2000Optimised"/>
      <xs:enumeration value="FaberRudy2000"/>
      <xs:enumeration value="DifrancescoNoble"/>
      <xs:enumeration value="MahajanShiferaw"/>
      <xs:enumeration value="HodgkinHuxley"/>
      <xs:enumeration value="tenTusscher2006"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ionic_model_region_type">
    <xs:sequence>
        <xs:element name="IonicModel" type="ionic_models_available_type"/>
        <xs:element name="Location" type="location_type"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ionic_models_type">
    <xs:sequence>
        <xs:element name="Default" type="ionic_models_available_type"/>
        <xs:element name="Region" type="ionic_model_region_type" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="apd_map_type">
    <xs:attribute name="repolarisation_percentage" type="xs:double" use="required"/>
    <xs:attribute name="threshold" type="xs:double" use="required"/>
    <xs:attribute name="threshold_unit" type="xs:string" use="required" fixed="mV"/>
  </xs:complexType>

  <xs:complexType name="upstrokes_map_type">
    <xs:attribute name="threshold" type="xs:double" use="required"/>
    <xs:attribute name="threshold_unit" type="xs:string" use="required" fixed="mV"/>
  </xs:complexType>

  <!-- Type with no content or attributes -->
  <xs:complexType name="empty_type">
  </xs:complexType>

  <xs:complexType name="conduction_velocity_map_type">
    <xs:attribute name="origin_node" type="xs:nonNegativeInteger" use="required"/>
  </xs:complexType>

  <xs:simpleType name="media_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Orthotropic"/>
      <xs:enumeration value="Axisymmetric"/>
      <xs:enumeration value="NoFibreOrientation"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="point_type">
    <xs:attribute name="x" type="xs:double" use="required"/>
    <xs:attribute name="y" type="xs:double" use="required"/>
    <xs:attribute name="z" type="xs:double" use="required"/>
  </xs:complexType>

  <xs:complexType name="box_type">
    <xs:sequence>
      <xs:element name="LowerCoordinates" type="point_type"/>
      <xs:element name="UpperCoordinates" type="point_type"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="stimulus_type">
    <xs:sequence>
      <xs:element name="Strength" type="stimulus_strength_type"/>
      <xs:element name="Duration" type="time_type"/>
      <xs:element name="Delay" type="time_type"/>
      <xs:element name="Location" type="location_type"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="cell_heterogeneity_type">
    <xs:sequence>
      <xs:element name="ScaleFactorGks" type="dimensionless_type"/>
      <xs:element name="ScaleFactorIto" type="dimensionless_type"/>
      <xs:element name="ScaleFactorGkr" type="dimensionless_type"/>
      <xs:element name="Location" type="location_type"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="conductivity_heterogeneity_type">
    <xs:all>
      <xs:element name="IntracellularConductivities" type="conductivities_type" minOccurs="0"/>
      <xs:element name="ExtracellularConductivities" type="conductivities_type" minOccurs="0"/>
      <xs:element name="Location" type="location_type"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="slab_type">
    <xs:attribute name="x" type="xs:double" use="required"/>
    <xs:attribute name="y" type="xs:double" use="required"/>
    <xs:attribute name="z" type="xs:double" use="required"/>
    <xs:attribute name="inter_node_space" type="xs:double" use="required"/>
  </xs:complexType>

  <xs:complexType name="sheet_type">
    <xs:attribute name="x" type="xs:double" use="required"/>
    <xs:attribute name="y" type="xs:double" use="required"/>
    <xs:attribute name="inter_node_space" type="xs:double" use="required"/>
  </xs:complexType>

  <xs:complexType name="fibre_type">
    <xs:attribute name="x" type="xs:double" use="required"/>
    <xs:attribute name="inter_node_space" type="xs:double" use="required"/>
  </xs:complexType>

  <xs:complexType name="load_mesh_type">
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="conductivity_media" type="media_type" use="required"/>
  </xs:complexType>


  <xs:complexType name="mesh_type">
      <xs:choice>
      <xs:element name="Slab" type="slab_type"/>
      <xs:element name="Sheet" type="sheet_type"/>
      <xs:element name="Fibre" type="fibre_type"/>
      <xs:element name="LoadMesh" type="load_mesh_type"/>
    </xs:choice>
    <xs:attribute name="unit" type="xs:string" use="required" fixed="cm"/>
  </xs:complexType>

  <xs:complexType name="conductivities_type">
    <xs:attribute name="longi" type="xs:double" use="required"/>
    <xs:attribute name="trans" type="xs:double" use="required"/>
    <xs:attribute name="normal" type="xs:double" use="required"/>
    <xs:attribute name="unit" type="xs:string" use="required" fixed="mS/cm"/>
  </xs:complexType>

  <xs:complexType name="time_steps_type">
    <xs:attribute name="ode" type="xs:double" use="required"/>
    <xs:attribute name="pde" type="xs:double" use="required"/>
    <xs:attribute name="printing" type="xs:double" use="required"/>
    <xs:attribute name="unit" type="xs:string" use="required" fixed="ms"/>
  </xs:complexType>

  <xs:simpleType name="ksp_use_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="relative"/>
      <xs:enumeration value="absolute"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ksp_tolerances_type">
    <xs:choice>
      <xs:element name="KSPRelative" type="xs:double"/>
      <xs:element name="KSPAbsolute" type="xs:double"/>
    </xs:choice>
  </xs:complexType>

  <xs:simpleType name="ksp_solver_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="cg"/>
      <xs:enumeration value="symmlq"/>
      <xs:enumeration value="gmres"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ksp_preconditioner_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ilu"/>
      <xs:enumeration value="jacobi"/>
      <xs:enumeration value="bjacobi"/>
      <xs:enumeration value="hypre"/>
      <xs:enumeration value="blockdiagonal"/>
      <xs:enumeration value="none"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="simulation_type">
    <xs:all>
      <xs:element name="SpaceDimension" type="xs:integer" minOccurs="0"/>
      <xs:element name="SimulationDuration" type="time_type" minOccurs="0"/>
      <xs:element name="Domain" type="domain_type" minOccurs="0"/>
      <xs:element name="Mesh" type="mesh_type" minOccurs="0"/>

      <xs:element name="IonicModels" type="ionic_models_type" minOccurs="0"/>

      <xs:element name="Stimuli" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Stimulus" type="stimulus_type" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name="CellHeterogeneities" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CellHeterogeneity" type="cell_heterogeneity_type" minOccurs="0" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name="ConductivityHeterogeneities" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
              <xs:element name="ConductivityHeterogeneity" type="conductivity_heterogeneity_type" minOccurs="0" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name="OutputDirectory" type="xs:string" minOccurs="0"/>
      <xs:element name="OutputFilenamePrefix" type="xs:string" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="physiological_type">
    <xs:all>
      <xs:element name="IntracellularConductivities" type="conductivities_type" minOccurs="0"/>
      <xs:element name="ExtracellularConductivities" type="conductivities_type" minOccurs="0"/>
      <xs:element name="BathConductivity" type="conductivity_type" minOccurs="0"/>
      <xs:element name="SurfaceAreaToVolumeRatio" type="inverse_length_type" minOccurs="0"/>
      <xs:element name="Capacitance" type="capacitance_type" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="numerical_type">
    <xs:all>
      <xs:element name="TimeSteps" type="time_steps_type" minOccurs="0"/>
      <xs:element name="KSPTolerances" type="ksp_tolerances_type" minOccurs="0"/>
      <xs:element name="KSPSolver" type="ksp_solver_type" minOccurs="0"/>
      <xs:element name="KSPPreconditioner" type="ksp_preconditioner_type" minOccurs="0"/>
    </xs:all>
  </xs:complexType>


  <xs:complexType name="postprocessing_type">
    <xs:sequence>
      <xs:element name="ActionPotentialDurationMap" type="apd_map_type" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="UpstrokeTimeMap" type="upstrokes_map_type" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="MaxUpstrokeVelocityMap" type="empty_type" minOccurs="0"/>
      <xs:element name="ConductionVelocityMap" type="conduction_velocity_map_type" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="chaste_parameters_type">
    <xs:sequence>
      <xs:element name="Simulation" type="simulation_type"/>
      <xs:element name="Physiological" type="physiological_type"/>
      <xs:element name="Numerical" type="numerical_type"/>
      <xs:element name="PostProcessing" type="postprocessing_type" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- The single root element.  All parameters files must start with this. -->
  <xs:element name="ChasteParameters" type="chaste_parameters_type"/>

</xs:schema>

=== Chaste/Chaste/heart/test/data/checkpoint_migration_via_xml/0.2ms/SaveBidomainShort_0.2ms/ChasteDefaults.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<cp20:ChasteParameters xmlns:cp20="https://chaste.comlab.ox.ac.uk/nss/parameters/2_0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/chaste/eclipse/workspace/Chaste/heart/src/io/ChasteParameters_1_1.xsd" xsi:schemaLocation="https://chaste.comlab.ox.ac.uk/nss/parameters/2_0 /home/chaste/eclipse/workspace/Chaste/heart/src/io/ChasteParameters_2_0.xsd">

  <cp20:Simulation>
    <cp20:SpaceDimension>3</cp20:SpaceDimension>
    <cp20:Domain>Mono</cp20:Domain>
    <cp20:IonicModels>
      <cp20:Default>
        <cp20:Hardcoded>LuoRudyI</cp20:Hardcoded>
      </cp20:Default>
    </cp20:IonicModels>
    <cp20:OutputDirectory>ChasteResults</cp20:OutputDirectory>
    <cp20:OutputFilenamePrefix>SimulationResults</cp20:OutputFilenamePrefix>
  </cp20:Simulation>

  <cp20:Physiological>
    <cp20:IntracellularConductivities longi="1.75" normal="1.75" trans="1.75" unit="mS/cm"/>
    <cp20:ExtracellularConductivities longi="7" normal="7" trans="7" unit="mS/cm"/>
    <cp20:BathConductivity unit="mS/cm">7</cp20:BathConductivity>
    <cp20:SurfaceAreaToVolumeRatio unit="1/cm">1400</cp20:SurfaceAreaToVolumeRatio>
    <cp20:Capacitance unit="uF/cm^2">1</cp20:Capacitance>
  </cp20:Physiological>

  <cp20:Numerical>
    <cp20:TimeSteps ode="0.01" pde="0.01" printing="0.01" unit="ms"/>
    <cp20:KSPTolerances>
      <cp20:KSPAbsolute>0.0002</cp20:KSPAbsolute>
    </cp20:KSPTolerances>
    <cp20:KSPSolver>cg</cp20:KSPSolver>
    <cp20:KSPPreconditioner>bjacobi</cp20:KSPPreconditioner>
  </cp20:Numerical>

  <cp20:PostProcessing/>

</cp20:ChasteParameters>

=== Chaste/Chaste/heart/test/data/checkpoints/purkinje_migration_archive/ChasteParameters.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<cp:ChasteParameters xmlns:cp="https://chaste.comlab.ox.ac.uk/nss/parameters/3_0" xmlns:cp20="https://chaste.comlab.ox.ac.uk/nss/parameters/2_0" xmlns:cp21="https://chaste.comlab.ox.ac.uk/nss/parameters/2_1" xmlns:cp22="https://chaste.comlab.ox.ac.uk/nss/parameters/2_2" xmlns:cp23="https://chaste.comlab.ox.ac.uk/nss/parameters/2_3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ChasteParameters_1_1.xsd" xsi:schemaLocation="https://chaste.comlab.ox.ac.uk/nss/parameters/3_0 ChasteParameters_3_0.xsd https://chaste.comlab.ox.ac.uk/nss/parameters/2_0 ChasteParameters_2_0.xsd https://chaste.comlab.ox.ac.uk/nss/parameters/2_1 ChasteParameters_2_1.xsd https://chaste.comlab.ox.ac.uk/nss/parameters/2_2 ChasteParameters_2_2.xsd https://chaste.comlab.ox.ac.uk/nss/parameters/2_3 ChasteParameters_2_3.xsd">

  <cp:Simulation>
    <cp:SpaceDimension>3</cp:SpaceDimension>
    <cp:Domain>Mono</cp:Domain>
    <cp:IonicModels>
      <cp:Default>
        <cp:Hardcoded>LuoRudyI</cp:Hardcoded>
      </cp:Default>
    </cp:IonicModels>
    <cp:OutputDirectory>ChasteResults</cp:OutputDirectory>
    <cp:OutputFilenamePrefix>SimulationResults</cp:OutputFilenamePrefix>
  </cp:Simulation>

  <cp:Physiological>
    <cp:IntracellularConductivities longi="1.75" normal="1.75" trans="1.75" unit="mS/cm"/>
    <cp:ExtracellularConductivities longi="7" normal="7" trans="7" unit="mS/cm"/>
    <cp:BathConductivity unit="mS/cm">7</cp:BathConductivity>
    <cp:SurfaceAreaToVolumeRatio unit="1/cm">1400</cp:SurfaceAreaToVolumeRatio>
    <cp:Capacitance unit="uF/cm^2">1</cp:Capacitance>
  </cp:Physiological>

  <cp:Numerical>
    <cp:TimeSteps ode="0.01" pde="0.01" printing="0.01" unit="ms"/>
    <cp:KSPTolerances>
      <cp:KSPAbsolute>0.0002</cp:KSPAbsolute>
    </cp:KSPTolerances>
    <cp:KSPSolver>cg</cp:KSPSolver>
    <cp:KSPPreconditioner>bjacobi</cp:KSPPreconditioner>
    <cp:MeshPartitioning>metis</cp:MeshPartitioning>
    <cp:UseStateVariableInterpolation>no</cp:UseStateVariableInterpolation>
  </cp:Numerical>

  <cp:PostProcessing/>

</cp:ChasteParameters>

=== Chaste/Chaste/heart/test/data/checkpoint_migration_via_xml/0.2ms/SaveBidomainShort_0.2ms/ChasteParameters.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<cp:ChasteParameters xmlns:cp="https://chaste.comlab.ox.ac.uk/nss/parameters/2017_1" xmlns:cp20="https://chaste.comlab.ox.ac.uk/nss/parameters/2_0" xmlns:cp21="https://chaste.comlab.ox.ac.uk/nss/parameters/2_1" xmlns:cp22="https://chaste.comlab.ox.ac.uk/nss/parameters/2_2" xmlns:cp23="https://chaste.comlab.ox.ac.uk/nss/parameters/2_3" xmlns:cp30="https://chaste.comlab.ox.ac.uk/nss/parameters/3_0" xmlns:cp31="https://chaste.comlab.ox.ac.uk/nss/parameters/3_1" xmlns:cp33="https://chaste.comlab.ox.ac.uk/nss/parameters/3_3" xmlns:cp34="https://chaste.comlab.ox.ac.uk/nss/parameters/3_4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ChasteParameters_1_1.xsd" xsi:schemaLocation="https://chaste.comlab.ox.ac.uk/nss/parameters/2017_1 ChasteParameters_2017_1.xsd https://chaste.comlab.ox.ac.uk/nss/parameters/2_0 ChasteParameters_2_0.xsd https://chaste.comlab.ox.ac.uk/nss/parameters/2_1 ChasteParameters_2_1.xsd https://chaste.comlab.ox.ac.uk/nss/parameters/2_2 ChasteParameters_2_2.xsd https://chaste.comlab.ox.ac.uk/nss/parameters/2_3 ChasteParameters_2_3.xsd https://chaste.comlab.ox.ac.uk/nss/parameters/3_0 ChasteParameters_3_0.xsd https://chaste.comlab.ox.ac.uk/nss/parameters/3_1 ChasteParameters_3_1.xsd https://chaste.comlab.ox.ac.uk/nss/parameters/3_3 ChasteParameters_3_3.xsd https://chaste.comlab.ox.ac.uk/nss/parameters/3_4 ChasteParameters_3_4.xsd">
  <cp:Simulation>
    <cp:SpaceDimension>3</cp:SpaceDimension>
    <cp:SimulationDuration unit="ms">0.2</cp:SimulationDuration>
    <cp:Domain>Bi</cp:Domain>
    <cp:Mesh unit="cm">
      <cp:Slab inter_node_space="0.01" x="0.1" y="0.1" z="0.1"/>
    </cp:Mesh>
    <cp:IonicModels>
      <cp:Default>
        <cp:Hardcoded>Fox2002BackwardEuler</cp:Hardcoded>
      </cp:Default>
    </cp:IonicModels>
    <cp:Stimuli>
      <cp:Stimulus>
        <cp:Strength unit="uA/cm^3">-80000</cp:Strength>
        <cp:Duration unit="ms">1</cp:Duration>
        <cp:Delay unit="ms">0</cp:Delay>
        <cp:Location unit="cm">
          <cp:Cuboid>
            <cp:LowerCoordinates x="0" y="0" z="0"/>
            <cp:UpperCoordinates x="0.1" y="1" z="1"/>
          </cp:Cuboid>
        </cp:Location>
      </cp:Stimulus>
    </cp:Stimuli>
    <cp:OutputDirectory>SaveBidomainShort</cp:OutputDirectory>
    <cp:OutputFilenamePrefix>SimulationResults</cp:OutputFilenamePrefix>
    <cp:OutputVisualizer cmgui="no" meshalyzer="yes" parallel_vtk="no" precision="0" vtk="no"/>
    <cp:CheckpointSimulation max_checkpoints_on_disk="3" timestep="0.2" unit="ms"/>
  </cp:Simulation>
  <cp:Physiological>
    <cp:IntracellularConductivities longi="1.75" normal="1.75" trans="1.75" unit="mS/cm"/>
    <cp:ExtracellularConductivities longi="7" normal="7" trans="7" unit="mS/cm"/>
    <cp:BathConductivity unit="mS/cm">7</cp:BathConductivity>
    <cp:SurfaceAreaToVolumeRatio unit="1/cm">1400</cp:SurfaceAreaToVolumeRatio>
    <cp:Capacitance unit="uF/cm^2">1</cp:Capacitance>
    <cp:Purkinje>
      <cp:SurfaceAreaToVolumeRatio unit="1/cm">2800</cp:SurfaceAreaToVolumeRatio>
      <cp:Capacitance unit="uF/cm^2">1</cp:Capacitance>
      <cp:Conductivity unit="mS/cm">1.75</cp:Conductivity>
    </cp:Purkinje>
  </cp:Physiological>
  <cp:Numerical>
    <cp:TimeSteps ode="0.01" pde="0.1" printing="0.1" unit="ms"/>
    <cp:KSPTolerances>
      <cp:KSPAbsolute>0.0002</cp:KSPAbsolute>
    </cp:KSPTolerances>
    <cp:KSPSolver>gmres</cp:KSPSolver>
    <cp:KSPPreconditioner>jacobi</cp:KSPPreconditioner>
    <cp:MeshPartitioning>parmetis</cp:MeshPartitioning>
    <cp:UseStateVariableInterpolation>no</cp:UseStateVariableInterpolation>
  </cp:Numerical>
</cp:ChasteParameters>
